server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: gateway
zuul:
  prefix: /api
  routes:
    user-service: /user/**
  ignored-services:
    - consumer-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectionTimeout: 500
  ReadTimeOut: 2000
  MaxAutoRetriesNextServer: 0
