server:
  port: 888
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    username: root
    password: liusu9686
#mybatis
mybatis:
  type-aliases-package: com.liu.model
  
  
logging:
  level:
    com.lotus.dao: INFO,DEBUG
  