server:
  port: 888
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false com.mysql.jdbc.Driver
    username: root
    password: liusu9686
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding.charset: UTF-8
    encoding.enabled: true
    encoding.force: true    
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html

#mybatis
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.liu.model
  
  
logging:
  level:
    com.lotus.dao: INFO,DEBUG
  